import os
import os
import sys
from pickle import TRUE
import platform

PIPELINE_LIB_PATH = os.environ.get("PIPELINE_LIB_PATH", "/home/evren_wsl/WORKSPACE_PERSONAL/Embedded_IoT_BT_WIFI_Base_Project/embedded_system/CI_CD")

if os.path.exists(PIPELINE_LIB_PATH):
    sys.path.append(PIPELINE_LIB_PATH)
else:
    print(f"⚠️ Warning: PIPELINE_LIB_PATH not found at {PIPELINE_LIB_PATH}")

class ProjectConfig:
    # ===========================================================
    # GENERAL SETTINGS
    # ===========================================================
    PROJECT_NAME = "Smart_Plug"
    # Resolves to 'smart_plug_project' root
    PROJECT_ROOT = os.getcwd()
    OUTPUT_DIR = os.path.join(PROJECT_ROOT, "Out")
    TEMP_WORKSPACE_NAME = "temp_workspace"

    CLONE_URL = "https://github.com/evrenkenanoglu/Smart_Plugs_SW.git"
    CLONE_BRANCH = "features/power_bar_app"
    CLONE_DIR = os.path.join(PROJECT_ROOT, OUTPUT_DIR, TEMP_WORKSPACE_NAME)
    WORKDIR = CLONE_DIR

    # ===========================================================
    # TOOLCHAIN SETTINGS
    # ===========================================================
    TOOLCHAIN = "esp-idf"
    TARGET = "esp32"
    ESP_IMAGE = "espressif/esp-matter:release-v1.4.2_idf_v5.4.1"
    ESP_IDF_EXPORT = "/opt/espressif/esp-idf/export.sh"
    ESP_MATTER_EXPORT = "/opt/espressif/esp-matter/export.sh"

    # ===========================================================
    # BUILD & ARTIFACT SETTINGS
    # ===========================================================
    USE_DOCKER = True

    # ===========================================================
    # RELEASE vs DEV SETTINGS
    # ===========================================================
    RELEASE = False
    PACKAGE_NAME = ""

    if RELEASE:
        VERSION = "0.1.0"
        PACKAGE_NAME = f"package_{PROJECT_NAME}_v{VERSION}"
    else:
        PACKAGE_NAME = f"package_{PROJECT_NAME}_dev"

    PACKAGE_DIR = os.path.join(PROJECT_ROOT, CLONE_DIR, PACKAGE_NAME)
    BUILD_DIR_NAME = "build"
    BUILD_DIR_PATH = os.path.join(PROJECT_ROOT, CLONE_DIR, BUILD_DIR_NAME)
    FACTORY_BIN_NAME = f"{PROJECT_NAME}_factory.bin"
    FACTORY_BIN_PATH = FACTORY_BIN_NAME

    ARTIFACT_NAME = os.path.join(OUTPUT_DIR, PACKAGE_NAME.replace("package_", ""))
    EXTRACTED_PACKAGE_DIR = os.path.join(PROJECT_ROOT, f"{ARTIFACT_NAME}_extracted")

    FLASH_ARGS_FILENAME = "flash_args"
    FLASH_ARGS_PATH = os.path.join(EXTRACTED_PACKAGE_DIR, FLASH_ARGS_FILENAME)
    PACKAGE_INCLUDES = [
        FACTORY_BIN_PATH,  # For Factory / HIL
        "*.bin",  # For OTA Updates
        "*.elf",  # For Crash Debugging
        "*.map",  # For Memory analysis
        "partitions.csv",  # Documentation
        "*flash_*",  # For Flashing (contains the flash_args file generated by idf.py)
    ]

    # ===========================================================
    # HIL TEST SETTINGS
    # ===========================================================
    HIL_TEST_DIR = os.path.join(PROJECT_ROOT, "example", "tests", "hil")

    DEFAULT_OTA_PORT = 8032
    SERIAL_PORT = "COM3" if platform.system().lower() == "windows" else "/dev/ttyUSB0"
    SERIAL_BAUD = 115200

    EMBEDDED_SERVICES = ["esp", "serial"]

    TEST_OUTPUT_DIR = os.path.join(OUTPUT_DIR, "test_reports")
    REPORT_FILE_PREFIX = "hil_report"

    TARGET_WIFI_SSID = "UniverseHome"
    TARGET_WIFI_PASSWORD = "Lotr_2023"

    CHIP_TOOL_PATH = "chip-tool"
