import logging
import shutil
import subprocess

logger = logging.getLogger("uvicorn.error")

def generate_delta_patch(base_path: str, new_path: str, patch_path: str) -> bool:
    """Generates a compressed patch by invoking the system's standalone detools CLI.
    
    This keeps the Python environment 100% cross-platform and compile-free,
    delegating binary operations to the host OS command line.
    """
    # 1. Dynamically locate the 'detools' executable in the system PATH
    detools_executable = shutil.which("detools") or shutil.which("detools.exe")
    
    if not detools_executable:
        logger.error(
            "The standalone 'detools' command-line executable was not found in the system PATH. "
            "Please ensure 'detools' is installed globally on your host OS."
        )
        return False
        
    try:
        # 2. Build the cross-platform command arguments
        cmd = [
            detools_executable,
            "create_patch",
            "-c", "heatshrink",
            base_path,
            new_path,
            patch_path
        ]
        
        logger.info(f"Executing system patch command: {' '.join(cmd)}")
        
        # 3. Spawn subprocess to execute the patch creation
        result = subprocess.run(
            cmd, 
            stdout=subprocess.PIPE, 
            stderr=subprocess.PIPE, 
            text=True, 
            check=True
        )
        
        logger.info("Patch file successfully generated by system compiler.")
        return True
        
    except subprocess.CalledProcessError as e:
        logger.error(f"detools system compiler failed with exit code {e.returncode}: {e.stderr}")
        return False
    except Exception as e:
        logger.error(f"Error spawning detools process: {e}")
        return False